---
- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - python-pip
    - python-dev
    - python-mysqldb
    - python3-pip
    - python3-dev
    - python3-mysqldb
    - build-essential

- name: Get latest version
  become: yes
  pip:
    name: pip
    extra_args: --upgrade

- name: Get latest version (pip3)
  become: yes
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Pip virtualenv
  become: yes
  pip:
    name: virtualenv

- name: Pip3 virtualenv
  become: yes
  pip:
    name: virtualenv
    executable: pip3

- name: Create venv directory
  become: yes
  file:
    path: "/usr/local/venvs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
