---
- name: Stage Setup
  hosts: web
  roles:
    # Server setup
    - { role: common }

    # Infrastructure
    - { role: mysql }
    - { role: redis }

    # Projects
    - { role: myproject-web, download_code: False }
  environment: "{{ env_vars }}"
